prometheus_node_targets:
  - 'localhost:9100'
  - '93.90.207.171:9100'

prometheus_blackbox_targets:
  - cyber-sec.net
  - www.cyber-sec.net

alertmanager_smtp_smarthost: 'smtp.1und1.de:456'
alertmanager_smtp_from: 'vafa.ronaghi@cyber-sec.net'
alertmanager_smtp_auth_username: 'vafa.ronaghi@cyber-sec.net'
alertmanager_smtp_auth_password: 'Startsk84ever'

alertmanager_route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: team-mails

alertmanager_receivers:
  - name: team-mails
    email_configs:
    - to: vafa.ronaghi@cyber-sec.net
